twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/bundles/easyadmin/manifest.json'

